version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ems-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - ems-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - GITHUB_BRANCH=${GITHUB_BRANCH}
        - GITHUB_BACKEND_REPO=${GITHUB_BACKEND_REPO}
    container_name: ems-backend
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - ems-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - GITHUB_BRANCH=${GITHUB_BRANCH:-main}
        - GITHUB_BACKEND_REPO=${GITHUB_BACKEND_REPO}
    container_name: ems_frontend
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - ems-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  ems-network:
    driver: bridge